name: Update gist with latest Bilibili videos
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9043f73e8354e5f5f2cb84594dcacdad
          UID: '23473446'
        run: deno run --allow-net --allow-env index.ts
